### ISSUE TITLE
Build fails for ubuntu:latest using docker (see fix below)

### ISSUE THREAD

**Issue by ctwhittle** [istopwg/ippsample#25] opened 2016-11-17 18:51 UTC
![2016 1171-ippsample-build-error](https://cloud.githubusercontent.com/assets/7174187/20402945/a2b63e0c-acb3-11e6-990d-fd5bf7984c2a.PNG)

**Comment by michaelrsweet** [comment] 2016-11-18 14:18
Should be addressed by: [master 772ac27] Sync up with CUPS upstream.

**Comment by wifiprintguy** [comment] 2016-11-29 21:53
What is needed to close this? Just git pull on the master branch and verify that the issue is resolved?

**Comment by michaelrsweet** [comment] 2016-11-29 22:38
Yes

**Comment by ctwhittle** [comment] 2016-11-30 01:41
Mike / Smith,

The issue has been resolved.  Thanks.

All the best,

**CW

**Closed** 2016-11-30 12:58 UTC
Labels: Medium
