### ISSUE TITLE
ippserver : Getting Printer error <filename> notification on client while printing an image using IPP server

### ISSUE THREAD

**Issue by WIPSivaG** [istopwg/ippsample#255] opened 2022-02-23 02:43 UTC
## Environment:
- Device/OS: Samsung/ Android 11
- Printer/Network: IPP server

## Steps to Reproduce
- On IPP server run the "run_PWGRaster" powershell script
- Open the image (attached below)
- Either share/print with MPS
- Select IPP server printer and click on print icon

## Additional Info
- IPP server is using 443 port ( So it is considered as secured- IPPS printer)
- Issue also reproducible with few other images as well.
- I could not reproduce on Pixel/Android 10 and Samsung/ Android 7 devices.

## Test data:
- Image test files [PrintData2.zip](https://github.com/istopwg/ippsample/files/8121514/PrintData2.zip)
- run_PWGRaster scripts:  [IPPServer_Scripts.zip](https://github.com/istopwg/ippsample/files/8131490/IPPServer_Scripts.zip)
- Packet capture: [Packet_Captures1.zip](https://github.com/istopwg/ippsample/files/8131494/Packet_Captures1.zip)

**Comment by wifiprintguy** [comment] 2022-02-23 02:50
Any packet captures (.pcapng etc.) or traces from ippserver? And where did this "run_PWGRaster" powershell script come from?

**Comment by WIPSivaG** [comment] 2022-02-24 09:58
@wifiprintguy 
Thanks for the reply. Please find the attached script files and packet capture in issue description.
Thanks.

**Comment by WIPSivaG** [comment] 2022-03-23 14:59
@wifiprintguy Could you please help us to find the resolution.
Thanks in advance.

**Comment by snappy-pickle** [comment] 2022-03-27 20:22
Sorry for taking a while to reply - I was on holiday this past week. Several comments / thoughts:

1. Port 443 is not needed for IPPS / IPP over TLS. IPP uses TCP port 631 for both IPP _and_ IPPS, as per [RFC 7472](https://www.rfc-editor.org/rfc/rfc7472.html).

2. The Packet_Captures1.pcapng file seems to expose very little that can be diagnosed - if IPP is being performed, it is concealed by the TLS connections.

3. There seem to be a number of TCP streams between the client DESKTOP-HE3T03A.local (192.168.0.4)
and the server 192.168.0.184 but only some of them seem to successfully connect. I'm not sure if some of these failures are connections where the client is expecting the server to allow a non-TLS IPP connection or what the failure is caused by.

Is this problem reproducible if the ippserver is run using unprotected IPP (e.g., no TLS)? And is this actually the PWG's ippserver?

**Comment by snappy-pickle** [comment] 2022-03-27 21:01
Also, what version of MPS are you using? You might want to bring this to the Mopria / MPS folks because it might be that it is a client problem, not an ippserver problem. But again, hard to know when things are protected via TLS.

**Comment by michaelrsweet** [comment] 2023-03-20 01:00
I think this might have been the Windows SSPI issues we were having in libcups, which have since been resolved. Closing for now, but if you can reproduce with current ippsample code then let me know.

**Closed by michaelrsweet** 2023-03-20 01:00 UTC
